---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r, results='hide', message=FALSE}
include <- function(library_name){
  if( !(library_name %in% installed.packages()) )
    install.packages(library_name) 
  library(library_name, character.only=TRUE)
}
include("rvest")
include("tidyr")
include("stringr")
```



```{r}
my_url <- "http://ems.csuchico.edu/APSS/schedule/spr2019/CSCI.shtml"
html1 <- read_html(my_url)
my_url <- "http://ems.csuchico.edu/APSS/schedule/spr2020/CSCI.shtml"
html2 <- read_html(my_url)
my_url <- "http://ems.csuchico.edu/APSS/schedule/spr2019/MATH.shtml"
html3 <- read_html(my_url)
my_url <- "http://ems.csuchico.edu/APSS/schedule/spr2020/MATH.shtml"
html4 <- read_html(my_url)
```

### This chunk does the actual scraping of the html
#### The function returns a tibble of the data scraped

```{r warning=FALSE}
read_class_schedule <- function(url) {

  classes <- url %>% html_nodes(".classrow")

  subject <- classes %>% 
              html_nodes("td.subj") %>% 
              html_text() 

  catNum <- classes %>% 
          html_nodes("td.cat_num") %>% 
          html_text() %>% 
          as.integer()

  sect <- classes %>% 
          html_nodes("td.sect") %>% 
          html_text() %>% 
          as.integer()

  type <- classes %>% 
          html_nodes("td.comp") %>% 
          html_text()

  title <- classes %>% 
          html_nodes("td.title") %>% 
          html_text()

  units <- classes %>% 
          html_nodes("td.units") %>% 
          html_text() %>%
          as.integer()

  instruct <- classes %>% 
            html_nodes("td.Instructor") %>% 
            html_text()

  totenro <- classes %>% 
            html_nodes("td.enrtot") %>% 
            html_text() %>%
            as.integer()
            
  temp <- url %>%
          html_nodes("#bd > div > div > h1") %>%
          html_text()

  pattern1 <- "(Spring|Fall)\ (\\d*)"
  yearSem <- tibble(strings=stringr::str_match_all(temp, pattern1))

  returned <- tibble(subject=subject, catNum=catNum,
                     sect=sect, type=type,
                     title=title, units=units,
                     instruct=instruct, totenro=totenro,
                     sem=yearSem$strings[[1]][1,2],
                     year=yearSem$strings[[1]][1,3])

  return(returned)
}

csci2019 <- read_class_schedule(html1)
head(csci2019)

csci2020 <- read_class_schedule(html2)
head(csci2020)

math2019 <- read_class_schedule(html3)
head(math2019)

math2020 <- read_class_schedule(html4)
head(math2020)

```
